from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.parsers import JSONParser
from .models import Amendment, RelatedLaw
from django.http import HttpResponse
import io

try:
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.utils import simpleSplit
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False

class CitationGeneratorView(APIView):
    permission_classes = [AllowAny]

    def get(self, request):
        law = request.query_params.get('law', 'The Act')
        section = request.query_params.get('section', '1')
        year = request.query_params.get('year', '2023')

        citations = {
            "APA": f"{law} ({year}). Section {section}.",
            "MLA": f"{law}. Sec. {section}, {year}.",
            "Bluebook": f"{law}, § {section} ({year}).",
            "Indian": f"{law} § {section} ({year}) (India)."
        }
        return Response(citations)

class PDFGeneratorView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        """GET-based PDF for simple short content."""
        law_title = request.query_params.get('law', 'Legal Document')
        content = request.query_params.get('content', 'Default content...')
        return self._generate_pdf(law_title, content)

    def post(self, request):
        """POST-based PDF for longer content that doesn't fit in URL."""
        law_title = request.data.get('law', 'Legal Document')
        content = request.data.get('content', 'Default content...')
        return self._generate_pdf(law_title, content)

    def _generate_pdf(self, law_title, content):
        if not HAS_REPORTLAB:
            return Response({"error": "ReportLab not installed."}, status=500)

        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{law_title}.pdf"'

        try:
            p = canvas.Canvas(response, pagesize=A4)
            width, height = A4
            margin = 72  # 1 inch margins
            y = height - margin

            # Title
            p.setFont("Helvetica-Bold", 16)
            p.drawString(margin, y, f"Report for: {law_title}")
            y -= 30

            # Separator line
            p.setStrokeColorRGB(0.3, 0.3, 0.8)
            p.line(margin, y, width - margin, y)
            y -= 20

            # Content with text wrapping
            p.setFont("Helvetica", 11)
            max_width = width - 2 * margin
            lines = []
            for paragraph in content.split('\n'):
                wrapped = simpleSplit(paragraph, "Helvetica", 11, max_width)
                lines.extend(wrapped if wrapped else [''])

            for line in lines:
                if y < margin + 20:
                    p.showPage()
                    p.setFont("Helvetica", 11)
                    y = height - margin
                p.drawString(margin, y, line)
                y -= 16

            # Footer
            p.setFont("Helvetica-Oblique", 8)
            p.drawString(margin, 40, "Generated by Civic Companion - Legal Intelligence Platform")

            p.showPage()
            p.save()
            return response
        except Exception as e:
            return Response({"error": f"PDF generation failed: {str(e)}"}, status=500)

class RelatedLawsView(APIView):
    permission_classes = [AllowAny]

    def get(self, request):
        law = request.query_params.get('law')
        section = request.query_params.get('section')

        if not law:
            return Response({"related_laws": []})

        filters = {'primary_law_table': law}
        if section:
            filters['primary_section_id'] = section

        related = RelatedLaw.objects.filter(**filters)
        results = [
            {
                "primary": f"{r.primary_law_table} § {r.primary_section_id}",
                "related": f"{r.related_law_table} § {r.related_section_id}",
                "relationship": r.relationship_type
            }
            for r in related
        ]
        return Response({"related_laws": results})

class AmendmentTrackingView(APIView):
    permission_classes = [AllowAny]

    def get(self, request):
        law = request.query_params.get('law')
        section = request.query_params.get('section')

        if not law:
            return Response({"amendments": []})

        filters = {'law_table': law}
        if section:
            filters['section_id'] = section

        amendments = Amendment.objects.filter(**filters).order_by('-date_enacted')
        results = [
            {
                "law_table": a.law_table,
                "section_id": a.section_id,
                "status": a.status,
                "description": a.description,
                "date_enacted": str(a.date_enacted)
            }
            for a in amendments
        ]
        return Response({"amendments": results})
