# Generated by Django 5.2.16 on 2026-08-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawtablelist',
            options={'managed': True},
        ),
    ]
