# Generated by Django 5.2.15 on 2026-07-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_table', models.CharField(max_length=100)),
                ('section_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('New', 'New'), ('Updated', 'Updated'), ('Repealed', 'Repealed'), ('Amended', 'Amended')], max_length=20)),
                ('description', models.TextField()),
                ('date_enacted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatedLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_law_table', models.CharField(max_length=100)),
                ('primary_section_id', models.CharField(max_length=100)),
                ('related_law_table', models.CharField(max_length=100)),
                ('related_section_id', models.CharField(max_length=100)),
                ('relationship_type', models.CharField(max_length=50)),
            ],
        ),
    ]
